export const STATUS_CARD_FIELDS = [
  ['fuelLevel', 'Fuel level'],
  ['engineRpm', 'Engine RPM'],
  ['power', 'Power'],
  ['coolant', 'Coolant'],
  ['engineRuntime', 'Engine runtime'],
  ['maf', 'Mass Air Flow'],
  ['intakeAir', 'Intake air'],
  ['throttle', 'Throttle'],
  ['ignition', 'Ignition'],
  ['obdSpeed', 'OBD speed'],
  ['gnssSpeed', 'GNSS speed'],
  ['controlVoltage', 'Control voltage'],
  ['satellites', 'GNSS satellites'],
  ['gnssStatus', 'GNSS status'],
  ['signalStrength', 'GSM signal'],
  ['trackerBatteryLevel', 'Tracker battery level'],
  ['batteryVoltage', 'Tracker battery voltage'],
  ['batteryCurrent', 'Tracker battery current'],
  ['fuelUsed', 'Fuel used (trip)'],
  ['fuelRate', 'Fuel rate'],
  ['barometricPressure', 'Barometric pressure'],
  ['absoluteLoad', 'Absolute load'],
  ['timingAdvance', 'Timing advance'],
  ['ambientAir', 'Ambient air temperature'],
  ['motion', 'Motion'],
  ['pdop', 'GNSS PDOP'],
  ['hdop', 'GNSS HDOP'],
  ['operator', 'GSM operator'],
  ['fuelRailPressure', 'Fuel rail pressure'],
  ['accelerometerX', 'Accelerometer X'],
  ['accelerometerY', 'Accelerometer Y'],
  ['accelerometerZ', 'Accelerometer Z'],
  ['segmentDistance', 'Segment distance'],
]

export const DEFAULT_STATUS_CARD_FIELDS = STATUS_CARD_FIELDS.map(([key]) => key)
