import { useEffect, useState } from 'react'
import { createAdminGroup, createAdminUser, deleteAdminGroup, deleteAdminUser, fetchAdminGroups, fetchAdminUsers, fetchAdminUserDevices, fetchAdminGroupDevices, fetchAdminGroupUsers, fetchAdminUserGroups, fetchAdminUserVehicles, fetchAdminGroupVehicles, setAdminUserDeviceAccess, setAdminGroupDeviceAccess, setAdminGroupMembership, setAdminGroupVehicleAccess, setAdminUserVehicleAccess, updateAdminUser } from '../lib/vehicleAppApi'

const blankUser = { username: '', password: '', firstName: '', lastName: '', email: '', role: 'regular', active: true, autoAccessNewDevices: false }
const blankGroup = { name: '', autoAccessNewDevices: false }
function Switch({ checked, onChange, label }) { return <label className="admin-switch"><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} /><span className="admin-switch-slider" /><span>{label}</span></label> }

export default function AdminAccessPanel({ baseUrl, isAdmin, vehicles = [], devices = [] }) {
  const [users, setUsers] = useState([]); const [groups, setGroups] = useState([]); const [status, setStatus] = useState('')
  const [editor, setEditor] = useState(null); const [tab, setTab] = useState('basic'); const [userDeviceIds, setUserDeviceIds] = useState([]); const [userVehicleIds, setUserVehicleIds] = useState([]); const [userGroupIds, setUserGroupIds] = useState([]); const [groupDeviceIds, setGroupDeviceIds] = useState([]); const [groupVehicleIds, setGroupVehicleIds] = useState([]); const [groupUserIds, setGroupUserIds] = useState([])
  const refresh = async () => { if (!isAdmin) return; try { const [u, g] = await Promise.all([fetchAdminUsers(baseUrl), fetchAdminGroups(baseUrl)]); setUsers(u); setGroups(g) } catch (e) { setStatus(e instanceof Error ? e.message : 'Unable to load access data.') } }
  useEffect(() => { refresh() }, [baseUrl, isAdmin])
  useEffect(() => { if (!editor?.id || editor.kind !== 'user' || editor.id === 'new') return; Promise.all([fetchAdminUserDevices(baseUrl, editor.id), fetchAdminUserVehicles(baseUrl, editor.id), fetchAdminUserGroups(baseUrl, editor.id)]).then(([d, v, g]) => { setUserDeviceIds(d); setUserVehicleIds(v); setUserGroupIds(g) }).catch(() => {}) }, [baseUrl, editor])
  useEffect(() => { if (!editor?.id || editor.kind !== 'group' || editor.id === 'new') return; Promise.all([fetchAdminGroupDevices(baseUrl, editor.id), fetchAdminGroupVehicles(baseUrl, editor.id), fetchAdminGroupUsers(baseUrl, editor.id)]).then(([d, v, u]) => { setGroupDeviceIds(d); setGroupVehicleIds(v); setGroupUserIds(u) }).catch(() => {}) }, [baseUrl, editor])
  if (!isAdmin) return null
  const openUser = (item) => { setEditor({ kind: 'user', id: item?.id || 'new', data: item ? { ...item, password: '' } : { ...blankUser } }); setTab('basic') }
  const openGroup = (item) => { setEditor({ kind: 'group', id: item?.id || 'new', data: item ? { ...item } : { ...blankGroup } }); setTab('basic') }
  const closeEditor = () => setEditor(null)
  const saveEditor = async (e) => { e.preventDefault(); try { if (editor.kind === 'user') { if (editor.id === 'new') await createAdminUser(baseUrl, editor.data); else await updateAdminUser(baseUrl, editor.id, editor.data) } else { if (editor.id === 'new') await createAdminGroup(baseUrl, editor.data); else { /* group basic update is handled by the group endpoint */ } } setStatus(`${editor.kind === 'user' ? 'User' : 'Group'} saved.`); closeEditor(); refresh() } catch (x) { setStatus(x instanceof Error ? x.message : 'Unable to save.') } }
  const toggle = async (kind, id, value, enabled) => { try { if (kind === 'device') { await (editor.kind === 'user' ? setAdminUserDeviceAccess(baseUrl, editor.id, id, enabled) : setAdminGroupDeviceAccess(baseUrl, editor.id, id, enabled)); const setter = editor.kind === 'user' ? setUserDeviceIds : setGroupDeviceIds; setter((x) => enabled ? [...new Set([...x, id])] : x.filter((v) => v !== id)) } else if (kind === 'vehicle') { await (editor.kind === 'user' ? setAdminUserVehicleAccess(baseUrl, editor.id, id, enabled) : setAdminGroupVehicleAccess(baseUrl, editor.id, id, enabled)); const setter = editor.kind === 'user' ? setUserVehicleIds : setGroupVehicleIds; setter((x) => enabled ? [...new Set([...x, id])] : x.filter((v) => v !== id)) } else { await setAdminGroupMembership(baseUrl, editor.id, id, enabled); const setter = editor.kind === 'user' ? setUserGroupIds : setGroupUserIds; setter((x) => enabled ? [...new Set([...x, id])] : x.filter((v) => v !== id)) } } catch (x) { setStatus(x instanceof Error ? x.message : 'Unable to update access.') } }
  const data = editor?.data || {}
  return <div className="profile-editor admin-access-panel"><h4>Users and Groups</h4><p className="profile-editor-help">Double-click a record to edit it. Device access controls live Traccar visibility; vehicle access controls historical data.</p>
    <div className="settings-grid admin-access-lists"><div><strong>Users ({users.length})</strong><ul>{users.map((u) => <li key={u.id}><button type="button" className={`admin-list-item ${editor?.kind === 'user' && editor.id === u.id ? 'active' : ''}`} onClick={() => openUser(u)} onDoubleClick={() => openUser(u)}>{u.username} · {u.role}</button><button type="button" className="admin-delete-button" onClick={async () => { if (window.confirm(`Delete user ${u.username}?`)) { await deleteAdminUser(baseUrl, u.id); refresh(); if (editor?.id === u.id) closeEditor() } }}>×</button></li>)}</ul></div><div><strong>Groups ({groups.length})</strong><ul>{groups.map((g) => <li key={g.id}><button type="button" className={`admin-list-item ${editor?.kind === 'group' && editor.id === g.id ? 'active' : ''}`} onClick={() => openGroup(g)} onDoubleClick={() => openGroup(g)}>{g.name}</button><button type="button" className="admin-delete-button" onClick={async () => { if (window.confirm(`Delete group ${g.name}?`)) { await deleteAdminGroup(baseUrl, g.id); refresh(); if (editor?.id === g.id) closeEditor() } }}>×</button></li>)}</ul></div></div>{status && <p className="profile-editor-status">{status}</p>}
    {editor && <div className="admin-access-editor"><div className="admin-tabs">{editor.kind === 'user' ? ['basic', 'devices', 'vehicles', 'groups'].map((x) => <button key={x} type="button" className={tab === x ? 'active' : ''} onClick={() => setTab(x)}>{x === 'basic' ? 'Basic info' : x[0].toUpperCase() + x.slice(1)}</button>) : ['basic', 'devices', 'vehicles', 'users'].map((x) => <button key={x} type="button" className={tab === x ? 'active' : ''} onClick={() => setTab(x)}>{x === 'basic' ? 'Basic info' : x[0].toUpperCase() + x.slice(1)}</button>)}</div>
      {tab === 'basic' && <form className="settings-grid" onSubmit={saveEditor}>{editor.kind === 'user' ? <><label>Username<input value={data.username} disabled={editor.id !== 'new'} onChange={(e) => setEditor({ ...editor, data: { ...data, username: e.target.value } })} required /></label><label>Password<input type="password" value={data.password || ''} onChange={(e) => setEditor({ ...editor, data: { ...data, password: e.target.value } })} placeholder={editor.id === 'new' ? '' : 'Leave blank to keep current'} required={editor.id === 'new'} /></label><label>First name<input value={data.firstName || ''} onChange={(e) => setEditor({ ...editor, data: { ...data, firstName: e.target.value } })} /></label><label>Last name<input value={data.lastName || ''} onChange={(e) => setEditor({ ...editor, data: { ...data, lastName: e.target.value } })} /></label><label>Email<input type="email" value={data.email || ''} onChange={(e) => setEditor({ ...editor, data: { ...data, email: e.target.value } })} /></label><label>Role<select value={data.role} onChange={(e) => setEditor({ ...editor, data: { ...data, role: e.target.value } })}><option value="regular">Regular</option><option value="admin">Administrator</option></select></label><Switch checked={data.autoAccessNewDevices} label="Auto-access future devices" onChange={(v) => setEditor({ ...editor, data: { ...data, autoAccessNewDevices: v } })} /></> : <><label>Group name<input value={data.name} onChange={(e) => setEditor({ ...editor, data: { ...data, name: e.target.value } })} required /></label><Switch checked={data.autoAccessNewDevices} label="Auto-access future devices" onChange={(v) => setEditor({ ...editor, data: { ...data, autoAccessNewDevices: v } })} /></>}<div className="actions two-up"><button type="submit">{editor.id === 'new' ? `Create ${editor.kind === 'user' ? 'User' : 'Group'}` : `Save ${editor.kind === 'user' ? 'User' : 'Group'}`}</button><button type="button" className="secondary" onClick={closeEditor}>Cancel</button></div></form>}
      {tab === 'devices' && <><p className="profile-editor-help">As defined in Traccar. These are hardware devices and their Traccar IDs, used for live device visibility.</p><div className="admin-toggle-grid">{devices.map((d) => <Switch key={d.id} checked={(editor.kind === 'user' ? userDeviceIds : groupDeviceIds).includes(Number(d.id))} label={`Traccar ID ${d.id} · ${d.name || 'Unnamed device'}`} onChange={(v) => toggle('device', Number(d.id), null, v)} />)}</div></>}
      {tab === 'vehicles' && <><p className="profile-editor-help">As defined in Traccar React. These catalog vehicles control access to historical trips and reports.</p><div className="admin-toggle-grid">{vehicles.map((v) => <Switch key={v.id} checked={(editor.kind === 'user' ? userVehicleIds : groupVehicleIds).includes(v.id)} label={v.displayName || v.name} onChange={(x) => toggle('vehicle', v.id, null, x)} />)}</div></>}
      {tab === 'groups' && <div className="admin-toggle-grid">{groups.map((g) => <Switch key={g.id} checked={userGroupIds.includes(g.id)} label={g.name} onChange={(x) => toggle('group', g.id, null, x)} />)}</div>}
      {tab === 'users' && <div className="admin-toggle-grid">{users.map((u) => <Switch key={u.id} checked={groupUserIds.includes(u.id)} label={u.username} onChange={(x) => toggle('user', u.id, null, x)} />)}</div>}
    </div>}
    <div className="actions two-up"><button type="button" onClick={() => openUser()}>New User</button><button type="button" onClick={() => openGroup()}>New Group</button></div>
  </div>
}
